# Generated by Django 3.0.8 on 2020-07-29 08:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_auto_20200729_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
