# Generated by Django 3.0.8 on 2020-07-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0007_auto_20200729_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
