# Generated by Django 3.0.8 on 2020-07-31 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Post', '0009_auto_20200730_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='Tag',
        ),
        migrations.AddField(
            model_name='blog',
            name='Author',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.IntegerField(blank=True),
        ),
    ]
