# Generated by Django 3.0.8 on 2020-07-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0010_auto_20200731_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='blog',
            name='Category',
            field=models.CharField(max_length=255),
        ),
    ]
