# Generated by Django 3.0.8 on 2020-08-01 12:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0011_auto_20200731_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 8, 1, 12, 41, 16, 601592, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='Post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Post.Blog'),
            preserve_default=False,
        ),
    ]
