# Generated by Django 3.0.8 on 2020-08-04 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0013_auto_20200801_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reply', models.TextField()),
                ('Name', models.CharField(max_length=200)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Replies', to='Post.Comment')),
            ],
        ),
    ]
